name: Build & Publish
on:
    push:
        branches:
            - main

jobs:
    build-site:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install Composer Dependencies
              run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            - name: Install NPM Dependencies
              run: npm install
            - name: Build Site
              run: make build@prod
            - name: Stage Files
              run: git add -f build_production
            - name: Commit files
              run: |
                  git config --local user.email "actions@github.com"
                  git config --local user.name "GitHub Actions"
                  git commit -m "Build for deploy"
            - name: Publish
              run: |
                  git subtree split --prefix build_production -b gh-pages
                  git push -f origin gh-pages:gh-pages
